FROM python:3.14-alpine

WORKDIR /app

# Install system dependencies
RUN apk add --no-cache --virtual .build-deps g++

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN apk del .build-deps

COPY . .

EXPOSE 8000

CMD ["python", "run.py"]